jobs:
  test:
    docker:
      - image: node:latest
      - image: redis:5
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run:
          name: test
          command: npm run test-most
          environment:
            REDIS_HOST: redis
            REDIS_PORT: 6379
workflows:
  version: 2
  test:
    jobs:
      - test
